// src/App.tsx
import { Session } from "@supabase/supabase-js"
import { useState, useEffect } from "react"
import Auth from './components/Auth'
import SaveWeight from "./components/SaveWeight"
import GetWeights from "./components/GetWeights"
import { supabase } from './helpers/supabase'

export default function App() {

  const [session, setSession] = useState<Session | null>(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  async function signOut() {
    const { error } = await supabase.auth.signOut()
  }


  return (
    <div className="container">
      {!session ?
        <Auth />
        :
        <div>
          <button onClick={signOut} >
            LogOut
          </button>
          <SaveWeight session={session} />
          <GetWeights session={session} />
        </div>
      }

    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import { watchEffect } from "vue";
import { RouterLink, RouterView } from 'vue-router'
import Auth from './components/Auth.vue'
import { supabase } from './helpers/supabase';
import { store } from './stores/store'


async function logData() {
  const { data, error } = await supabase.auth.getSession()
  console.log(data)
  console.log(store.session)
}

watchEffect(async () => {
  const { data, error } = await supabase.auth.getSession()

  if (data != null) {
    store.session = data
    console.log(store.session)
  }

})

async function signOut() {
  const { error } = await supabase.auth.signOut()
}
</script>

<template>
  <header>
    <div class="wrapper">
      <Auth />
      <button @click="logData">Console Log Session</button>
      <button @click="signOut">Log Out</button>
      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/saveweight">Save Weight</RouterLink>
        <RouterLink to="/showweight">Show Weight History</RouterLink>
      </nav>
    </div>
  </header>
  <RouterView />
</template>
